name: "build-package"
description: "Install package and build example"
inputs:
  install:
    default: "true"
    description: "Install the package after build"
  build_type:
    description: "Type of build (e.g., cmake or conan)"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/install-conan

    - name: Run conan install
      shell: bash
      run: conan install .

    - name: Build package
      shell: bash
      run: |
        if [ "$(uname)" == "Linux" ]; then
          cmake --preset conan-release
        else
          cmake --preset conan-default
        fi

    - name: Install package
      if: ${{inputs.install == 'true' }}
      run: cmake --install build
      shell: bash
    # - name: Build example
    #   if: ${{inputs.install == 'true' }}
    #   shell: bash
    #   run: |
    #     mkdir examples/build
    #     cd examples/build
    #     cmake ..
    #     cmake --build .
