name: "build-package-vcpkg"
description: "Install package with vcpkg and build example"

runs:
  using: "composite"
  steps:

    - name: Build package
      shell: bash
      run: |
        cmake -B build/Release -DDREDUCT_CPP_USE_STD_CHRONO=OFF \
          -DREDUCT_CPP_ENABLE_TESTS=ON \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build build/Release
