name: "build-package-vcpkg"
description: "Install package with vcpkg and build example"
inputs:
  build_tests:
    default: "false"
  install:
    default: "true"
    description: "Install the package after build"
runs:
  using: "composite"
  steps:
    - name: Build package
      shell: bash
      run: |
        cmake -B build -DREDUCT_CPP_ENABLE_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
