name: "install-vcpkg"
description: "Install vcpkg and check its version"

runs:
  using: "composite"
  steps:
    - name: Install vcpkg
      shell: bash
      run: |
        cd ..
        git clone https://github.com/microsoft/vcpkg.git
        pwd
        cd vcpkg && ./bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=/workspaces/vcpkg" >> $GITHUB_ENV
        echo "PATH=$VCPKG_ROOT:$PATH" >> $GITHUB_PATH
        vcpkg version

    - name: Check vcpkg version
      shell: bash
      run: |
        vcpkg version
