name: "run-tests"
description: "Pull storage and run tests"
inputs:
  api-token: # id of input
    description: "API_TOKEN"
    required: false
    default: ""
  tags: # id of input
    description: "Tags for tests"
    required: false
    default: ""
  reductstore-version: # id of input
    description: "Reduct Store version"
    required: false
    default: "main"
  lic_file: # id of input
    description: "License file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run Reduct Store
      shell: bash
      run: docker run -p 8383:8383 -v ${PWD}:/workdir
        --env RS_API_TOKEN=${{inputs.api-token}}
        --env RS_LICENSE_PATH=/workdir/${{inputs.lic_file}}
        --name reduct-store
        -d reduct/store:${{inputs.reductstore-version}}
    - name: Print logs
      shell: bash
      run: |
        sleep 5
        docker logs reduct-store
    - name: Run tests
      shell: bash
      run: REDUCT_CPP_TOKEN_API=${{inputs.api-token}} build/Release/bin/reduct-tests ${{inputs.tags}}
